dist: xenial
language: python
sudo: false
addons:
  chrome: stable
matrix:
  include:
    - python: "2.7"
      env: PLONE_VERSION=5.0.x
    - python: "2.7"
      env: PLONE_VERSION=5.1.x
    - python: "2.7"
      env: PLONE_VERSION=5.2.x
    - python: "3.7"
      env: PLONE_VERSION=5.2.x
  fast_finish: true
cache:
  pip: true
  directories:
  - eggs
  - downloads
before_install:
  - pip install -U pip
  - pip install --ignore-installed six
  - mkdir webdriver; export PATH=$(pwd)/webdriver:$PATH
  - pip install webdrivermanager; webdrivermanager chrome --linkpath $(pwd)/webdriver
  - pip install -r https://github.com/plone/buildout.coredev/raw/$PLONE_VERSION/requirements.txt
install:
  - buildout -Nc test-$PLONE_VERSION.cfg annotate
  - buildout -Nc test-$PLONE_VERSION.cfg
before_script:
  - 'export DISPLAY=:99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - sleep 3
script:
  - bin/code-analysis
  - bin/test --all
  - bin/createcoverage -t '--all'
after_success:
  - pip install -q coveralls
  - coveralls
